apiVersion: v1
kind: Service
metadata:
  name: saleor-api
  labels: {{- include "saleor.labels" . | nindent 4 }}
spec:
  selector:
    app: saleor-api
  ports:
    - port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-api
  labels: {{- include "saleor.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: saleor-api
  template:
    metadata:
      labels:
        app: saleor-api
    spec:
      {{- include "saleor.fastFailover" . | nindent 6 }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: saleor-api
      containers:
        - name: api
          image: {{ .Values.images.api }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              memory: 1Gi
          env: {{- include "saleor.env" . | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
