apiVersion: v1
kind: Secret
metadata:
  name: saleor-secrets
  labels: {{- include "saleor.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ required "set saleor.secretKey" .Values.saleor.secretKey | quote }}
  postgres-password: {{ required "set postgres.password" .Values.postgres.password | quote }}
  database-url: "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.database }}"
